import { Component, ComponentFactoryResolver, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import CommonFunction from '../common/common-functions';
import Translation from '../classes/translation.class';

@Component({
    selector: 'app-activity',
    templateUrl: '../module-base/views/base.component.html',
    styleUrls: ['../module-base/views/base.component.scss']
  })
  export class LanguageService {

    protected commonFunction: CommonFunction;

    private nameEntity: String = 'language';
    private params: String = '';
  
    arrayTranslations: Translation[] = [];

    //MAINPANE
    private LABELAPPOINTMENTS: number= 0;
    private LABELTODAYSMEALS: number= 1;
    private LABELDEPOSITIONS: number= 2;
    private LABELNAPS: number= 3;
    private LABELSTATISTICS: number= 4;
    
    //OPTIONS LEFT SIDE MENU
    private LABELOPTIONMAINPANE: number= 5;
    private LABELOPTIONUSERS: number= 6;
    private LABELOPTIONSUPERADMINCONFIG: number= 7;
    private LABELOPTIONKINDERGARTEN: number= 8;
    private LABELOPTIONSCHOOLS: number= 9;
    private LABELOPTIONCOURSES: number= 10;
    private LABELOPTIONGROUPS: number= 11;
    private LABELOPTIONTEACHERS: number= 12;
    private LABELOPTIONSTAFF: number= 13;
    private LABELOPTIONPSYCHOLOGISTS: number= 14;
    private LABELOPTIONMENUS: number= 15;
    private LABELOPTIONDISHES: number= 16;
    private LABELOPTIONINTOLERANCES: number= 17;
    private LABELOPTIONSTUDENTS: number= 18;
    private LABELOPTIONACTIVITIES: number= 19;
    private LABELOPTIONHOMEWORKS: number= 20;
    private LABELOPTIONPARENTS: number= 21;
    private LABELOPTIONPAYMENTS: number= 22;
    private LABELOPTIONCOURSESENROLL: number= 23;
    private LABELOPTIONSTAFFREG: number= 24;
    private LABELOPTIONPSYCHOLOGISTREG: number= 25;
    private LABELOPTIONMENUASSIGNMENT: number= 26;
    private LABELOPTIONACTIVITIESINSC: number= 27;
    private LABELOPTIONMYGROUP: number= 28;
    private LABELOPTIONCOURSEREG: number= 29;
    private LABELOPTIONPARENTCHAT: number= 30;
    private LABELOPTIONTUTORCHAT: number= 31;
    private LABELOPTIONUPLOADPICTURE: number= 32;
    private LABELOPTIONAPPOINTMENTPSYCHOLOGIST: number= 33;
    private LABELOPTIONAPPOINTMENTTUTOR: number= 34;
    private LABELTODAYSMENU: number= 35;
    private LABELBREAKFAST: number= 36;
    private LABELSTARTER: number= 37;
    private LABELMAIN: number= 38;
    private LABELDESSERT: number= 39;
    private LABELSNACK: number= 40;
    private LABELLOGOUT: number= 41;
    private LABELSTUDENTFILE: number= 42;
    private LABELDNI: number= 43;
    private LABELNAME: number= 44;
    private LABELSURNAME: number= 45;
    private LABELRESP1: number= 46;
    private LABELRESP2: number= 47;
    private LABELINTOLERANCES: number= 48;
    private LABELTODAYSREG: number= 49;
    private LABELNUMBERDEP: number= 50;
    private LABELMEAL: number= 51;
    private LABELNAP: number= 52;
    private LABELREMARKS: number= 53;
    private LABELUSERSMANAGEMENT: number= 54;
    private LABELUSERNAME: number= 55;
    private LABELMODIFY: number= 56;
    private LABELNEW: number= 57;
    private LABELUSER: number= 58;
    private LABELPASSWORD: number= 59;
    private LABELTYPE: number= 60;
    private LABELSAVE: number= 61;
    private LABELCANCEL: number= 62;
    private LABELUPDATE: number= 63;
    private LABELDELETE: number= 64;
    private LABELADDNEW: number= 65;
    private LABELKINDERGARTEN: number= 66;
    private LABELSCHOOL: number= 67;
    private LABELCOURSE: number= 68;
    private LABELGROUP: number= 69;
    private LABELTEACHER: number= 70;
    private LABELSTAFF: number= 71;
    private LABELPSYCHOLOGIST: number= 72;
    private LABELMENU: number= 73;
    private LABELDISH: number= 74;
    private LABELINTOLERANCE: number= 75;
    private LABELSTUDENT: number= 76;
    private LABELACTIVITY: number= 77;
    private LABELHOMEWORK: number= 78;
    private LABELPARENT: number= 79;
    private LABELGROUPSMANAGEMENT: number= 80;
    private LABELTEACHERSMANAGEMENT: number= 81;
    private LABELSTAFFMANAGEMENT: number= 82;
    private LABELPSYCHOLOGISTMANAGEMENT: number= 83;
    private LABELMENUMANAGEMENT: number= 84;
    private LABELDISHMANAGEMENT: number= 85;
    private LABELINTOLERANCESMANAGEMENT: number= 86;
    private LABELSTUDENTSMANAGEMENT: number= 87;
    private LABELGENRE: number= 88;
    private LABELMALE: number= 89;
    private LABELFEMALE: number= 90;
    private LABELDATEBIRTH: number= 91;
    private LABELDAY: number= 92;
    private LABELMONTH: number= 93;
    private LABELYEAR: number= 94;
    private LABELACTIVITIESMANAGEMENT: number= 95;
    private LABELHOMEWORKMANAGEMENT: number= 96;
    private LABELPARENTSMANAGEMENT: number= 97;
    private LABELFATHER: number= 98;
    private LABELMOTHER: number= 99;
    private LABELTUTOR: number= 100;
    private LABELENROLLMENTSMANAGEMENT: number= 101;
    private LABELFEE: number= 102;
    private LABELENROLLMENT: number= 103;
    private LABELVIEW: number= 104;
    private LABELGROUPENROLLMENT: number= 105;
    private LABELCOURSEENROLLMENT: number= 106;    
    private LABELDAILYMENUASSIGNMENT: number= 107;    
    private LABELASSIGNMENU: number= 108;    
    private LABELASSIGN: number= 109;        
    
    constructor(){
        this.commonFunction= new CommonFunction(); 
        this.commonFunction.write('constructor '+this.nameEntity+'Service', '');
        this.initializeValues();
    }

    private initializeValues(){
      this.arrayTranslations.push(new Translation('Incoming appointments', 'Citas previstas'));
      this.arrayTranslations.push(new Translation('Todays meals', 'Menu del día'));
      this.arrayTranslations.push(new Translation('Depositions', 'Deposiciones'));
      this.arrayTranslations.push(new Translation('Naps', 'Siestas'));
      this.arrayTranslations.push(new Translation('Statistics', 'Estadísticas'));
      this.arrayTranslations.push(new Translation('Main pane', 'Panel principal'));
      this.arrayTranslations.push(new Translation('Users', 'Usuarios'));
      this.arrayTranslations.push(new Translation('Site config', 'Configuración del site'));
      this.arrayTranslations.push(new Translation('Kindergarten', 'Guarderias'));
      this.arrayTranslations.push(new Translation('Schools', 'Centros'));
      this.arrayTranslations.push(new Translation('Courses', 'Cursos'));
      this.arrayTranslations.push(new Translation('Groups', 'Grupos'));
      this.arrayTranslations.push(new Translation('Teachers', 'Profesores'));
      this.arrayTranslations.push(new Translation('Staff', 'Personal'));
      this.arrayTranslations.push(new Translation('Psychologists', 'Psicólogos'));
      this.arrayTranslations.push(new Translation('Menus', 'Menús'));
      this.arrayTranslations.push(new Translation('Dishes', 'Platos'));
      this.arrayTranslations.push(new Translation('Intolerances', 'Intolerancias'));
      this.arrayTranslations.push(new Translation('Students', 'Alumnos'));
      this.arrayTranslations.push(new Translation('Activities', 'Actividades'));
      this.arrayTranslations.push(new Translation('Homeworks', 'Tareas'));
      this.arrayTranslations.push(new Translation('Parents', 'Padres'));
      this.arrayTranslations.push(new Translation('Payments', 'Pagos'));
      this.arrayTranslations.push(new Translation('Courses enrollment', 'Matriculaciones'));
      this.arrayTranslations.push(new Translation('Staff registration', 'Asignación de personal'));
      this.arrayTranslations.push(new Translation('Psychologists registration', 'Asignación de psicologos'));
      this.arrayTranslations.push(new Translation('Menu assignment', 'Asignación de menús'));
      this.arrayTranslations.push(new Translation('Activities inscription', 'Inscripción en actividades'));
      this.arrayTranslations.push(new Translation('My group', 'My grupo'));
      this.arrayTranslations.push(new Translation('Course registration', 'Registro de curso'));
      this.arrayTranslations.push(new Translation('Parent chat', 'Chat de padres'));
      this.arrayTranslations.push(new Translation('Chat with the tutor', 'Chat con el tutor'));
      this.arrayTranslations.push(new Translation('Upload a picture', 'Subir una imagen'));
      this.arrayTranslations.push(new Translation('Appointment with psychologist', 'Cita con el psicologo'));
      this.arrayTranslations.push(new Translation('Appointment with tutor', 'Cita con el tutor'));
      this.arrayTranslations.push(new Translation('Today\'s menu','Menú del día'));
      this.arrayTranslations.push(new Translation('Breakfast','Desayuno'));
      this.arrayTranslations.push(new Translation('Starter','Entrante'));
      this.arrayTranslations.push(new Translation('Main','Principal'));
      this.arrayTranslations.push(new Translation('Dessert','Postre'));
      this.arrayTranslations.push(new Translation('Snack','Merienda'));
      this.arrayTranslations.push(new Translation('Logout','Desconectar'));
      this.arrayTranslations.push(new Translation('Student File','Ficha de alumno'));
      this.arrayTranslations.push(new Translation('DNI','DNI'));
      this.arrayTranslations.push(new Translation('Name','Nombre'));
      this.arrayTranslations.push(new Translation('Surname','Apellidos'));
      this.arrayTranslations.push(new Translation('Responsable 1','Responsable 1'));
      this.arrayTranslations.push(new Translation('Responsable 2','Responsable 2'));
      this.arrayTranslations.push(new Translation('intolerances','Intolerancias'));
      this.arrayTranslations.push(new Translation('Today\'s register','Registro de hoy'));
      this.arrayTranslations.push(new Translation('Number of depositions','Numero de deposiciones'));
      this.arrayTranslations.push(new Translation('Meal','Comida'));
      this.arrayTranslations.push(new Translation('Nap','Siesta'));
      this.arrayTranslations.push(new Translation('Remarks','Comentarios'));
      this.arrayTranslations.push(new Translation('Users management','Administración de usuarios'));
      this.arrayTranslations.push(new Translation('Username','Nombre de usuario'));
      this.arrayTranslations.push(new Translation('Modify','Modificar'));
      this.arrayTranslations.push(new Translation('New','Nuevo'));
      this.arrayTranslations.push(new Translation('user','usuario'));
      this.arrayTranslations.push(new Translation('Password','Contraseña'));
      this.arrayTranslations.push(new Translation('Type','Tipo'));
      this.arrayTranslations.push(new Translation('Save','Guardar'));
      this.arrayTranslations.push(new Translation('Cancel','Cancelar'));
      this.arrayTranslations.push(new Translation('Update','Actualizar'));
      this.arrayTranslations.push(new Translation('Delete','Eliminar'));
      this.arrayTranslations.push(new Translation('Add new','Añadir nuevo'));
      this.arrayTranslations.push(new Translation('kindergarten', 'guarderia'));
      this.arrayTranslations.push(new Translation('school', 'centro'));
      this.arrayTranslations.push(new Translation('course', 'curso'));
      this.arrayTranslations.push(new Translation('group', 'grupo'));
      this.arrayTranslations.push(new Translation('teacher', 'profesor'));
      this.arrayTranslations.push(new Translation('staff', 'personal'));
      this.arrayTranslations.push(new Translation('psychologist', 'psicólogo'));
      this.arrayTranslations.push(new Translation('menu', 'menú'));
      this.arrayTranslations.push(new Translation('dish', 'plato'));
      this.arrayTranslations.push(new Translation('intolerance', 'intolerancia'));
      this.arrayTranslations.push(new Translation('student', 'alumno'));
      this.arrayTranslations.push(new Translation('activity', 'actividad'));
      this.arrayTranslations.push(new Translation('homework', 'tarea'));
      this.arrayTranslations.push(new Translation('parent', 'padre'));
      this.arrayTranslations.push(new Translation('Groups management','Administración de grupos'));
      this.arrayTranslations.push(new Translation('Teachers management','Administración de profesores'));
      this.arrayTranslations.push(new Translation('Staff management','Administración de personal'));
      this.arrayTranslations.push(new Translation('Psychologists management','Administración de psicólogos'));
      this.arrayTranslations.push(new Translation('Menus management','Administración de menús'));
      this.arrayTranslations.push(new Translation('Dishes management','Administración de platos'));
      this.arrayTranslations.push(new Translation('Intolerances management','Administración de intolerancias'));
      this.arrayTranslations.push(new Translation('Students management','Administración de alumnos'));
      this.arrayTranslations.push(new Translation('Genre','Género'));
      this.arrayTranslations.push(new Translation('Male','Masculino'));
      this.arrayTranslations.push(new Translation('Female','Femenino'));
      this.arrayTranslations.push(new Translation('Date of birth','Fecha de nacimiento'));
      this.arrayTranslations.push(new Translation('Day','Día'));
      this.arrayTranslations.push(new Translation('Month','Mes'));
      this.arrayTranslations.push(new Translation('Year','Año'));
      this.arrayTranslations.push(new Translation('Activities management','Administración de actividades'));
      this.arrayTranslations.push(new Translation('Homework management','Administración de tareas'));
      this.arrayTranslations.push(new Translation('Parents management','Administración de padres'));
      this.arrayTranslations.push(new Translation('Father','Padre'));
      this.arrayTranslations.push(new Translation('Mother','Madre'));
      this.arrayTranslations.push(new Translation('Tutor','Tutor'));
      this.arrayTranslations.push(new Translation('Enrollment management','Administración de matrículas'));
      this.arrayTranslations.push(new Translation('Fee','Cuota'));
      this.arrayTranslations.push(new Translation('enrollment','matrícula'));
      this.arrayTranslations.push(new Translation('View','Ver'));
      this.arrayTranslations.push(new Translation('Group','Grupo'));
      this.arrayTranslations.push(new Translation('Course','Curso'));
      this.arrayTranslations.push(new Translation('Daily menu assignment','Asignación de menú diario'));
      this.arrayTranslations.push(new Translation('Assign menu','Asignar menú'));
      this.arrayTranslations.push(new Translation('Assign','Asignar'));
      //console.log(this.arrayTranslations);      
      this.arrayTranslations.push(new Translation('',''));
    }

    public getWord(lang: number, label: string){      
      //this.commonFunction.write('getWord', 'lang: '+lang+' label: '+label);
      return this.arrayTranslations[this.getValueOfLabel(label)].getValue(lang);
    }

    public getValueOfLabel(label: string){
      //this.commonFunction.write('getValueOfLabel', label);
      switch(label){
        case 'LABELAPPOINTMENTS':                 return this.LABELAPPOINTMENTS;break;
        case 'LABELTODAYSMEALS':                  return this.LABELTODAYSMEALS;break;
        case 'LABELDEPOSITIONS':                  return this.LABELDEPOSITIONS;break;
        case 'LABELNAPS':                         return this.LABELNAPS;break;
        case 'LABELSTATISTICS':                   return this.LABELSTATISTICS;break;          
        case 'LABELOPTIONMAINPANE':               return this.LABELOPTIONMAINPANE;break;
        case 'LABELOPTIONUSERS':                  return this.LABELOPTIONUSERS;break;
        case 'LABELOPTIONSUPERADMINCONFIG':       return this.LABELOPTIONSUPERADMINCONFIG;break;
        case 'LABELOPTIONKINDERGARTEN':           return this.LABELOPTIONKINDERGARTEN;break;
        case 'LABELOPTIONSCHOOLS':                return this.LABELOPTIONSCHOOLS;break;
        case 'LABELOPTIONCOURSES':                return this.LABELOPTIONCOURSES;break;
        case 'LABELOPTIONGROUPS':                 return this.LABELOPTIONGROUPS;break;
        case 'LABELOPTIONTEACHERS':               return this.LABELOPTIONTEACHERS;break;
        case 'LABELOPTIONSTAFF':                  return this.LABELOPTIONSTAFF;break;
        case 'LABELOPTIONPSYCHOLOGISTS':          return this.LABELOPTIONPSYCHOLOGISTS;break;
        case 'LABELOPTIONMENUS':                  return this.LABELOPTIONMENUS;break;
        case 'LABELOPTIONDISHES':                 return this.LABELOPTIONDISHES;break;
        case 'LABELOPTIONINTOLERANCES':           return this.LABELOPTIONINTOLERANCES;break;
        case 'LABELOPTIONSTUDENTS':               return this.LABELOPTIONSTUDENTS;break;
        case 'LABELOPTIONACTIVITIES':             return this.LABELOPTIONACTIVITIES;break;
        case 'LABELOPTIONHOMEWORKS':              return this.LABELOPTIONHOMEWORKS;break;
        case 'LABELOPTIONPARENTS':                return this.LABELOPTIONPARENTS;break;
        case 'LABELOPTIONPAYMENTS':               return this.LABELOPTIONPAYMENTS;break;
        case 'LABELOPTIONCOURSESENROLL':          return this.LABELOPTIONCOURSESENROLL;break;
        case 'LABELOPTIONSTAFFREG':               return this.LABELOPTIONSTAFFREG;break;
        case 'LABELOPTIONPSYCHOLOGISTREG':        return this.LABELOPTIONPSYCHOLOGISTREG;break;
        case 'LABELOPTIONMENUASSIGNMENT':         return this.LABELOPTIONMENUASSIGNMENT;break;
        case 'LABELOPTIONACTIVITIESINSC':         return this.LABELOPTIONACTIVITIESINSC;break;
        case 'LABELOPTIONMYGROUP':                return this.LABELOPTIONMYGROUP;break;
        case 'LABELOPTIONCOURSEREG':              return this.LABELOPTIONCOURSEREG;break;
        case 'LABELOPTIONPARENTCHAT':             return this.LABELOPTIONPARENTCHAT;break;
        case 'LABELOPTIONTUTORCHAT':              return this.LABELOPTIONTUTORCHAT;break;
        case 'LABELOPTIONUPLOADPICTURE':          return this.LABELOPTIONUPLOADPICTURE;break;        
        case 'LABELOPTIONAPPOINTMENTPSYCHOLOGIST':return this.LABELOPTIONAPPOINTMENTPSYCHOLOGIST;break;
        case 'LABELOPTIONAPPOINTMENTTUTOR':       return this.LABELOPTIONAPPOINTMENTTUTOR;break;
        case 'LABELTODAYSMENU':                   return this.LABELTODAYSMENU;break;
        case 'LABELBREAKFAST':                    return this.LABELBREAKFAST;break;
        case 'LABELSTARTER':                      return this.LABELSTARTER;break;
        case 'LABELMAIN':                         return this.LABELMAIN;break;
        case 'LABELDESSERT':                      return this.LABELDESSERT;break;
        case 'LABELSNACK':                        return this.LABELSNACK;break;
        case 'LABELLOGOUT':                       return this.LABELLOGOUT;break;
        case 'LABELSTUDENTFILE':                  return this.LABELSTUDENTFILE;break;
        case 'LABELDNI':                          return this.LABELDNI;break;
        case 'LABELNAME':                         return this.LABELNAME;break;
        case 'LABELSURNAME':                      return this.LABELSURNAME;break;
        case 'LABELRESP1':                        return this.LABELRESP1;break;
        case 'LABELRESP2':                        return this.LABELRESP2;break;
        case 'LABELINTOLERANCES':                 return this.LABELINTOLERANCES;break;
        case 'LABELTODAYSREG':                    return this.LABELTODAYSREG;break;
        case 'LABELNUMBERDEP':                    return this.LABELNUMBERDEP;break;
        case 'LABELMEAL':                         return this.LABELMEAL;break;
        case 'LABELNAP':                          return this.LABELNAP;break;
        case 'LABELREMARKS':                      return this.LABELREMARKS;break;
        case 'LABELUSERSMANAGEMENT':              return this.LABELUSERSMANAGEMENT;break;
        case 'LABELUSERNAME':                     return this.LABELUSERNAME;break;
        case 'LABELMODIFY':                       return this.LABELMODIFY;break;
        case 'LABELNEW':                          return this.LABELNEW;break;
        case 'LABELUSER':                         return this.LABELUSER;break;
        case 'LABELPASSWORD':                     return this.LABELPASSWORD;break;
        case 'LABELTYPE':                         return this.LABELTYPE;break;
        case 'LABELSAVE':                         return this.LABELSAVE;break;
        case 'LABELCANCEL':                       return this.LABELCANCEL;break;
        case 'LABELUPDATE':                       return this.LABELUPDATE;break;
        case 'LABELDELETE':                       return this.LABELDELETE;break;
        case 'LABELADDNEW':                       return this.LABELADDNEW;break;
        case 'LABELKINDERGARTEN':                 return this.LABELKINDERGARTEN;break;
        case 'LABELSCHOOL':                       return this.LABELSCHOOL;break;
        case 'LABELCOURSE':                       return this.LABELCOURSE;break;
        case 'LABELGROUP':                        return this.LABELGROUP;break;
        case 'LABELTEACHER':                      return this.LABELTEACHER;break;
        case 'LABELSTAFF':                        return this.LABELSTAFF;break;
        case 'LABELPSYCHOLOGIST':                 return this.LABELPSYCHOLOGIST;break;
        case 'LABELMENU':                         return this.LABELMENU;break;
        case 'LABELDISH':                         return this.LABELDISH;break;
        case 'LABELINTOLERANCE':                  return this.LABELINTOLERANCE;break;
        case 'LABELSTUDENT':                      return this.LABELSTUDENT;break;
        case 'LABELACTIVITY':                     return this.LABELACTIVITY;break;
        case 'LABELHOMEWORK':                     return this.LABELHOMEWORK;break;
        case 'LABELPARENT':                       return this.LABELPARENT;break;
        case 'LABELGROUPSMANAGEMENT':             return this.LABELGROUPSMANAGEMENT;break;
        case 'LABELTEACHERSMANAGEMENT':           return this.LABELTEACHERSMANAGEMENT;break;
        case 'LABELSTAFFMANAGEMENT':              return this.LABELSTAFFMANAGEMENT;break;
        case 'LABELPSYCHOLOGISTMANAGEMENT':       return this.LABELPSYCHOLOGISTMANAGEMENT;break;
        case 'LABELMENUMANAGEMENT':               return this.LABELMENUMANAGEMENT;break;
        case 'LABELDISHMANAGEMENT':               return this.LABELDISHMANAGEMENT;break;
        case 'LABELINTOLERANCESMANAGEMENT':       return this.LABELINTOLERANCESMANAGEMENT;break;
        case 'LABELSTUDENTSMANAGEMENT':           return this.LABELSTUDENTSMANAGEMENT;break;
        case 'LABELGENRE':                        return this.LABELGENRE;break;
        case 'LABELMALE':                         return this.LABELMALE;break;
        case 'LABELFEMALE':                       return this.LABELFEMALE;break;
        case 'LABELDATEBIRTH':                    return this.LABELDATEBIRTH;break;
        case 'LABELDAY':                          return this.LABELDAY;break;
        case 'LABELMONTH':                        return this.LABELMONTH;break;
        case 'LABELYEAR':                         return this.LABELYEAR;break;
        case 'LABELACTIVITIESMANAGEMENT':         return this.LABELACTIVITIESMANAGEMENT;break;
        case 'LABELHOMEWORKMANAGEMENT':           return this.LABELHOMEWORKMANAGEMENT;break;
        case 'LABELPARENTSMANAGEMENT':            return this.LABELPARENTSMANAGEMENT;break;
        case 'LABELFATHER':                       return this.LABELFATHER;break;
        case 'LABELMOTHER':                       return this.LABELMOTHER;break;
        case 'LABELTUTOR':                        return this.LABELTUTOR;break;
        case 'LABELENROLLMENTSMANAGEMENT':        return this.LABELENROLLMENTSMANAGEMENT;break;
        case 'LABELFEE':                          return this.LABELFEE;break;
        case 'LABELENROLLMENT':                   return this.LABELENROLLMENT;break;
        case 'LABELVIEW':                         return this.LABELVIEW;break;
        case 'LABELGROUPENROLLMENT':              return this.LABELGROUPENROLLMENT;break;
        case 'LABELCOURSEENROLLMENT':             return this.LABELCOURSEENROLLMENT;break;
        case 'LABELDAILYMENUASSIGNMENT':          return this.LABELDAILYMENUASSIGNMENT;break;
        case 'LABELASSIGNMENU':                   return this.LABELASSIGNMENU;break;
        case 'LABELASSIGN':                   return this.LABELASSIGN;break;
        //case '':                       return this.;break;
        default:                                  return -1;break;
      }
    }

  }
 


